# Site settings
title: Raina DeVries
# leave 'author:' blank!
author:
  name: Raina DeVries
  email: rpdevries@uchicago.edu

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  Paleontologist at the University of Chicago.

#  Write an awesome description for your new site here. You can edit this line
#  in _config.yml. It will appear in your document head meta (for Google search
#  results) and in your feed.xml site description.

# Build settings

theme: minima
# alt formula below
# remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Theme-specific settings

minima:
  # Minima date format.
  # Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
  #
  # date_format: "%b %-d, %Y"

  # Generate social links in footer.
  #
  social_links:
    - { platform: instagram,      user_url: "https://www.instagram.com/rainapelta" }
    #- { platform: threads,        user_url: "https://www.threads.net/@rainapelta" }
    - { platform: twitter,        user_url: "https://twitter.com/rainapelta" }
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/raina-devries-o214" }
    - { platform: researchgate,   user_url: "https://www.researchgate.net/profile/Raina-Devries" }
    - { platform: orcid,          user_url: "https://orcid.org/0000-0001-8246-5503" }
    #- { platform: google_scholar, user_url: "https://scholar.google.com/citations?hl=en&user=Gaq7eOUAAAAJ" }
    
  #   - { platform: youtube,        user_url: "https://www.youtube.com" }
  #   - { platform: github,         user_url: "https://github.com/jekyll/minima" }
  #   - { platform: facebook,       user_url: "https://www.facebook.com" }

# If you want to link only specific pages in your header, uncomment this and add the path to the pages in
# order as they should show up.
#
# Page oranization on the header bar
header_pages:
  # - Posts.md
  - Publications.md
  - Contact.md

# Set to `true` to show excerpts on the homepage.
#
show_excerpts: true

# Enable Google Analytics
google_analytics: G-JTDGESVZ7C #UA-NNNNNNNN-N

# Gallery folder urls
imagesurl: "/assets/gallery/"
postsurl: "/assets/posts-gallery/"
thumbsurl: "/assets/gallery/thumbs"
